dash-client/test: resolve remaining data races
These data races were caused by an error that was hidden by the
data races themselves. With this diff applied, the following
is the error that started all this data-races focused work:

```
=== RUN   TestMain
--- FAIL: TestMain (14.01s)
    main_test.go:51: Post https://127.0.0.1:50743/negotiate/dash: http: server gave HTTP response to HTTPS client
FAIL
FAIL	github.com/neubot/dash/cmd/dash-client	14.033s
FAIL
```

I am going to fix this issue in the next commit.